version: "3.5"

services:

  mongo:
    image: mongo:5.0.7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: training
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"

  core:
    build: ../core
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: "${MONGODB_USERNAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"

  minio:
    image: minio/minio:edge
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server /data --console-address ":9001"

networks:
  default:
    external:
      name: external-core_edge

